#!/bin/sh

set -e

# if [ -d dist ]; then
# 	rm dist -rf
# fi
# mkdir dist
# cd dist
# brython-cli --install

rm dist -rf
cp ~/.local/lib/python3.8/site-packages/brython/data dist -r     # Can't and won't figure out how to get above to work
cd dist

rm README.txt
rm demo.html
rm index.html
cd ..

python3 preprocessor.py $1 /tmp/$1
# pyminifier /tmp/$1 > dist/$1
cp /tmp/$1 dist/$1

cat << EOF > dist/index.html
<html>
	<head>
		<meta charset="utf-8">
		<script type="text/javascript" src="brython.js"></script>
		<script type="text/javascript" src="brython_stdlib.js"></script>	
		<script type="text/python" src="brow.py" id="browpy"></script>
		<script type="text/python" src="$1"></script>
	</head>
	<body onload="brython()"></body>
</html>
EOF

# pyminifier brow.py > dist/brow.py
cp brow.py dist/brow.py
cd dist
python3 -m http.server --bind localhost
